name: analyzer_studio
description: A desktop app for comparing different options
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  system_theme: ^2.1.0
  window_manager: ^0.3.0
  flutter_acrylic: ^1.0.0+2
  provider: ^6.0.5
  fluent_ui: ^4.4.0
  flutter_layout_grid: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
